import 'package:flutter/material.dart';

class AppColors {
  const AppColors._();

  static const background = Color(0xFFFFFDFB);
  static const primary = Color(0xFFF4D7D7);
  static const accent = Color(0xFF5A4636);

  static const surface = Color(0xFFFFFFFF);
  static const surfaceTint = Color(0xFFFFF7F2);
  static const homeTodayCard = Color(0x94FFECE8);
  static const primarySoft = Color(0xFFFFECEC);
  static const primarySoft72 = Color(0xB8FFECE8);
  static const primaryPressed = Color(0xFFEFC9C9);
  static const textPrimary = accent;
  static const textSecondary = Color(0xFF826B59);
  static const textMuted = Color(0xFFA88E7E);
  static const aiPromptText = Color(0xFF715846);
  static const outline = Color(0xFFE9DDD4);
  static const bottomNavigation = Color(0xF5FFFFFF);
  static const coffeeVisualSurface = Color(0xB8FFFFFF);
  static const coffeeStickerOutline = Color(0xFFFFFFFF);
  static const coffeeStickerShadow = Color(0x1F5A4636);
  static const widgetCoffeeCard = Color(0xFFFFEFE4);
  static const widgetLatteGlassSurface = Color(0x75FFF8F3);
  static const widgetLatteGlassBorder = Color(0x47FFFFFF);
  static const widgetLatteGlassHighlight = Color(0x33FFFFFF);
  static const widgetLatteGlassTextProtection = Color(0x25FFF4E8);
  static const widgetLatteGlassTextLift = Color(0x0EFFFDF8);
  static const widgetLatteGlassShadow = Color(0x147C5C46);
  static const widgetLatteGlassInnerShadow = Color(0x0A000000);
  static const widgetAddButtonSurface = Color(0x35FFFFFF);
  static const widgetAddButtonBorder = Color(0x45FFFFFF);
  static const widgetAddButtonIcon = Color(0xCC6B4E3D);
  static const widgetStickerShadow = Color(0x145A4636);
  static const previewBackground = Color(0xFFF7F0EA);
  static const previewShadow = Color(0x1A5A4636);
  static const cardShadow = Color(0x145A4636);
  static const homeCardShadow = Color(0x0D5A4636);
  static const dimOverlay = Color(0x29000000);
  static const sheetHandle = outline;
  static const recordSheetShadow = Color(0x1F5A4636);
  static const recordOptionSurface = Color(0xEBFFFDFB);
  static const recordOptionShadow = Color(0x125A4636);
  static const recordIconBubble = Color(0xC7FFECE8);
  static const selectedChip = Color(0xB8F4D7D7);
  static const unselectedChip = Color(0xD1FFFDFB);
  static const homeEditActionSurface = Color(0xFFFFF7F2);
  static const homeDeleteActionSurface = Color(0xFFFFECEC);
  static const homeDeleteActionText = Color(0xFF9A6A62);
  static const homePrimaryButton = Color(0xFFB08F78);
  static const disabledButton = Color(0xFFE4DAD2);
  static const disabledButtonText = Color(0xFFA88E7E);
  static const journalMonthLabel = Color(0xFF9E7D66);
  static const journalTodayHighlight = Color(0xFFF4D7D7);
  static const journalBadgeSurface = Color(0xFFE9CACA);
  static const latteGlassSurface = Color(0xCCFFFFFD);
  static const latteGlassBorder = Color(0xB8E9DDD4);
  static const latteGlassHighlight = Color(0x5CFFF7F0);
  static const latteGlassTransparent = Color(0x00FFFFFD);
  static const latteGlassShadow = Color(0x145A4636);
  static const aiCandyGlassBase = Color(0x75FFFDFB);
  static const aiCandyGlassPink = Color(0x9CF4D7D7);
  static const aiCandyGlassCream = Color(0xB3FFF7F2);
  static const aiCandyGlassCoffee = Color(0x3D826B59);
  static const aiCandyGlassHighlight = Color(0x99FFFFFF);
  static const aiCandyGlassBorder = Color(0xB8FFFFFF);
  static const aiCandyGlassShadow = Color(0x1A5A4636);
  static const memoryOverlay = Color(0x7A332E29);
  static const memoryHandle = Color(0xFFE5D4C7);
}
